import Head from 'next/head'
import Avatar from '../components/Avatar'
import {Squares2X2Icon,MicrophoneIcon, MagnifyingGlassCircleIcon, MagnifyingGlassIcon} from '@heroicons/react/24/solid'
import Image from 'next/image'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'
export default function Home() {
  const router=useRouter();
  const searchInputRef=useRef(null);
  const Search=(e)=>{
    e.preventDefault();
    const term=searchInputRef.current.value;
    if(!term) return;
    router.push(`/search?term=${term}`)
  }
  return (
    <div className='relative h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://pbs.twimg.com/profile_images/1455185376876826625/s1AjSxph_400x400.jpg" className="rounded-full" />
      </Head>
       <header className="flex w-full p-5 justify-between text-sm text-gray-700 font-medium">
        <div className="flex space-x-4 items-center">
        <a href="https://about.google/">About</a>
        <a href="https://www.google.com/shopping">Store</a>
        </div>
        <div className="flex space-x-4 items-center">
         <a href="https://mail.google.com/">Gmail</a>
         <a href="https://www.google.com.pk/imghp?hl=en">Images</a>
          <Squares2X2Icon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
         <Avatar url={"https://pbs.twimg.com/profile_images/1455185376876826625/s1AjSxph_400x400.jpg"}/>
        </div>
       </header>
       <form className="flex flex-col items-center mt-44">
        <Image src="https://www.google.com.pk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
        width="300"
        height="100"
        alt="Google"
        />
        <div className="flex w-full hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border-2 border-gray-200 items-center px-5 py-3 sm:max-w-xl lg:max-w-2xl mt-3">
       <MagnifyingGlassIcon onClick={Search}  className="h-5 mr-3 text-gray-500 cursor-pointer"/>
       <input ref={searchInputRef} type="text" className="focus:outline-none flex-grow"/>
       <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 mt-8 justify-center sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={Search} className="btn">Google Search</button>
          <button onClick={Search} className="btn">I am Feeling Lucky</button>
        </div>
       </form>
      <div className="absolute bottom-0 left-0 w-full">
      <Footer />
      </div>
    </div>
  )
}
